# Generated by Django 4.0.1 on 2022-03-05 19:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('post_code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('rating', models.IntegerField(default=0)),
                ('phone_number', models.CharField(max_length=15)),
                ('logo', models.ImageField(upload_to='restaurant_images/')),
                ('background_image', models.ImageField(upload_to='restaurant_images/')),
                ('restaurant_image1', models.ImageField(upload_to='restaurant_images/')),
                ('restaurant_image2', models.ImageField(blank=True, null=True, upload_to='restaurant_images/')),
                ('restaurant_image3', models.ImageField(blank=True, null=True, upload_to='restaurant_images/')),
                ('belongs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(default=0)),
                ('menu_image', models.ImageField(upload_to='menu_images/')),
                ('description', models.CharField(max_length=1000)),
                ('belong', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='products.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('comment_body', models.CharField(max_length=500)),
                ('comment_image', models.ImageField(blank=True, null=True, upload_to='comment_images/')),
                ('comment_time', models.DateTimeField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('belong', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField()),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('blog_body', models.CharField(max_length=5000)),
                ('blog_title', models.CharField(max_length=200)),
                ('belong', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='products.restaurant')),
            ],
        ),
    ]
