# Generated by Django 4.0.1 on 2022-03-06 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_restaurant_belongs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='belong',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='products.restaurant'),
        ),
    ]
