# Generated by Django 4.0.1 on 2022-03-08 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_blog_ld'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_ld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=7, null=True, validators=[products.models.action_validator])),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lds', to='products.comment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ld_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
