# Generated by Django 4.0.3 on 2022-03-13 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0008_alter_restaurant_background_image_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Restaurant_ld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=7, null=True, validators=[products.models.action_validator])),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lds', to='products.restaurant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ld_restaurant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
