# Generated by Django 4.0.1 on 2022-03-14 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_restaurant_dislike_restaurant_like_restaurant_ld'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant_image',
            old_name='belong',
            new_name='restaurant',
        ),
        migrations.CreateModel(
            name='Restaurant_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='restaurant_images/')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='products.restaurant')),
            ],
        ),
    ]
