# Generated by Django 4.0.1 on 2022-03-14 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_belong_restaurant_image_restaurant_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant_images',
        ),
    ]
