# Generated by Django 4.0.1 on 2022-03-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_delete_restaurant_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='followers',
            field=models.IntegerField(default=0),
        ),
    ]
