# Generated by Django 4.0.1 on 2022-04-15 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_restaurant_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 15, 15, 3, 42, 236823)),
            preserve_default=False,
        ),
    ]
